#!/usr/bin/env python3
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 1.0.4 on Tue Sep 20 15:00:24 2022
#
import matplotlib.pyplot as plt
from pyparsing import alphas
from numpy.random import randn
import numpy as np
import time
from VRCom import *
import ctypes
import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class MyDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: MyDialog.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.SetTitle("shipParam")

        sizer_1 = wx.BoxSizer(wx.VERTICAL)

        sizer_3 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_3, 1, wx.EXPAND, 0)

        label_1 = wx.StaticText(self, wx.ID_ANY, "shipID:")
        sizer_3.Add(label_1, 0, 0, 0)

        self.text_ctrl_shipID = wx.TextCtrl(self, wx.ID_ANY, "")
        sizer_3.Add(self.text_ctrl_shipID, 0, 0, 0)

        self.button_start = wx.Button(self, wx.ID_ANY, "start")
        sizer_3.Add(self.button_start, 0, 0, 0)

        sizer_4 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_1.Add(sizer_4, 1, wx.EXPAND, 0)

        self.button_show = wx.Button(self, wx.ID_ANY, "show")
        sizer_4.Add(self.button_show, 0, 0, 0)

        sizer_2 = wx.StdDialogButtonSizer()
        sizer_1.Add(sizer_2, 0, wx.ALIGN_RIGHT | wx.ALL, 4)

        self.button_OK = wx.Button(self, wx.ID_OK, "")
        self.button_OK.SetDefault()
        sizer_2.AddButton(self.button_OK)

        self.button_CANCEL = wx.Button(self, wx.ID_CANCEL, "")
        sizer_2.AddButton(self.button_CANCEL)

        sizer_1.Add((0, 0), 0, 0, 0)

        sizer_2.Realize()

        self.SetSizer(sizer_1)
        sizer_1.Fit(self)

        self.SetAffirmativeId(self.button_OK.GetId())
        self.SetEscapeId(self.button_CANCEL.GetId())

        self.Layout()

        self.Bind(wx.EVT_BUTTON, self.showOrHideFigure, self.button_show)
        # end wxGlade

    #开始接收数据
    def startFigure(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'startFigure' not implemented!")
        event.Skip()

    #表格初始化设置
    def initFigureSet(self):
        fig=plt.figure()
        ax1=fig.add_subplot(2,2,1)
        ax2=fig.add_subplot(2,2,2)
        ax3=fig.add_subplot(2,2,3)
        ax4=fig.add_subplot(2,2,4)
    
        ax4.plot(np.arange(10))
        ax3.plot(randn(50).cumsum(),'k--')
        ax1.hist(randn(100),bins=20,color='k',alpha=0.3)
        ax2.scatter(np.arange(30),np.arange(30)+3*randn(30))

    def showOrHideFigure(self, event):  # wxGlade: MyDialog.<event_handler>
        print("Event handler 'showOrHideFigure' not implemented!")
        event.Skip()
# end of class MyDialog

class MyApp(wx.App):
    def OnInit(self):
        self.dialog = MyDialog(None, wx.ID_ANY, "")
        self.SetTopWindow(self.dialog)
        self.dialog.ShowModal()
        self.dialog.Destroy()
        return True

# end of class MyApp

if __name__ == "__main__":
    InitVRCom()
    CreateClient()

    app = MyApp(0)
    app.MainLoop()

    plt.show()
    ClearVRCom()
